org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

simple_version=0.8.3
mod_version=0.8.3+1.21.10
maven_group=com.tiers
archives_base_name=tiers

fabric_version=0.138.4+1.21.10

modmenu_version=16.0.1