org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

simple_version=0.7.2
mod_version=0.7.2+1.21.4
maven_group=com.tiers
archives_base_name=tiers

fabric_version=0.119.4+1.21.4

modmenu_version=13.0.3