name: Build Minecraft Mod

on:
  push:
    # Triggers on commits to any branch
    branches:
      - '**'
  workflow_dispatch:
    # Adds a button in GitHub Actions tab to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25s
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Upload built JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.ref_name }}
          path: build/libs/*.jar
